version: '3'
services:

    frontend-react:
        build:
            context: ./
            dockerfile: Dockerfile.local
        container_name: frontend-react
        volumes:
            - ./:/home
        ports:
            - "3000:3000"

