name: 'deploy'

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push to dokku
        uses: idoberko2/dokku-deploy-github-action@v1
        with:
          # git_remote_url: 'ssh://dokku@react-frontend.gustavotorregrosa.link:22/react-frontend'
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          dokku-host: 'react-frontend.gustavotorregrosa.link'
          app-name: 'react-frontend'
